### ISSUE TITLE
hero section

### ISSUE THREAD

**Issue by TahirAlauddin** [TahirAlauddin/Personal-Portfolio#16]
![image](https://github.com/user-attachments/assets/6c7a9bbd-fc14-4a9b-b120-b4e93fa8b72c)

**Comment by Absleepy** [comment]
This is how hero section looks like:

![image](https://github.com/user-attachments/assets/b93bf45e-2c93-4c2b-b498-003eee3d73c9)

**Comment by TahirAlauddin** [comment]
yaar mere laptop me abhi bhi wase hi dekha raha

**Comment by TahirAlauddin** [comment]
https://github.com/user-attachments/assets/4ee267fc-f594-4960-9723-7c8f5f0409cf

Attaching a video to help you out with the screen sizes where it's breaking.
it's perfectly fine in mobile phones which is awesome because most people are on phones.
